import { initDb } from './connection';
import { initializeSchema } from './schema';
import { queryOne, executeInsert } from './helpers';

const categories = [
  { name_ar: 'القرآن الكريم', name_en: 'Quran' },
  { name_ar: 'التفسير', name_en: 'Tafsir' },
  { name_ar: 'الحديث النبوي', name_en: 'Hadith' },
  { name_ar: 'السيرة النبوية', name_en: 'Seerah' },
  { name_ar: 'الأنبياء', name_en: 'Prophets' },
  { name_ar: 'الصحابة', name_en: 'Companions' },
  { name_ar: 'التاريخ الإسلامي', name_en: 'IslamicHistory' },
  { name_ar: 'الفقه', name_en: 'Fiqh' },
  { name_ar: 'العقيدة', name_en: 'Aqeedah' },
  { name_ar: 'الآداب الإسلامية', name_en: 'IslamicManners' },
  { name_ar: 'رمضان', name_en: 'Ramadan' },
  { name_ar: 'الحج والعمرة', name_en: 'HajjAndUmrah' },
  { name_ar: 'عام', name_en: 'General' },
];

const questions: {
  categoryName: string;
  question_ar: string;
  option_a: string;
  option_b: string;
  option_c: string;
  option_d: string;
  correct_answer: 'A' | 'B' | 'C' | 'D';
  difficulty: number;
  source?: string;
}[] = [
  // ====== القرآن الكريم ======
  { categoryName: 'القرآن الكريم', question_ar: 'كم عدد سور القرآن الكريم؟', option_a: '110', option_b: '114', option_c: '120', option_d: '124', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي أطول سورة في القرآن؟', option_a: 'سورة آل عمران', option_b: 'سورة النساء', option_c: 'سورة البقرة', option_d: 'سورة الأعراف', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي أقصر سورة في القرآن؟', option_a: 'سورة الناس', option_b: 'سورة الفلق', option_c: 'سورة الإخلاص', option_d: 'سورة الكوثر', correct_answer: 'D', difficulty: 1 },
  { categoryName: 'القرآن الكريم', question_ar: 'كم عدد آيات القرآن الكريم؟', option_a: '6236', option_b: '6000', option_c: '6348', option_d: '6200', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تسمى قلب القرآن؟', option_a: 'سورة البقرة', option_b: 'سورة يس', option_c: 'سورة الرحمن', option_d: 'سورة الواقعة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تسمى عروس القرآن؟', option_a: 'سورة طه', option_b: 'سورة الكهف', option_c: 'سورة مريم', option_d: 'سورة الرحمن', correct_answer: 'D', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تبدأ بـ "الم"؟', option_a: 'سورة البقرة', option_b: 'سورة آل عمران', option_c: 'سورة العنكبوت', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'في أي سورة وردت آية الكرسي؟', option_a: 'سورة آل عمران', option_b: 'سورة البقرة', option_c: 'سورة النساء', option_d: 'سورة المائدة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تسمى سنام القرآن؟', option_a: 'سورة البقرة', option_b: 'سورة يس', option_c: 'سورة الملك', option_d: 'سورة الرحمن', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'كم عدد أجزاء القرآن الكريم؟', option_a: '20', option_b: '25', option_c: '30', option_d: '35', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تسمى السبع المثاني؟', option_a: 'سورة البقرة', option_b: 'سورة الفاتحة', option_c: 'سورة الإخلاص', option_d: 'سورة الناس', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'في أي سورة وردت قصة أصحاب الكهف؟', option_a: 'سورة الكهف', option_b: 'سورة الإسراء', option_c: 'سورة مريم', option_d: 'سورة طه', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي لا تبدأ بالبسملة؟', option_a: 'سورة الفاتحة', option_b: 'سورة التوبة', option_c: 'سورة النمل', option_d: 'سورة هود', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'كم مرة ذكرت كلمة "الجنة" في القرآن؟', option_a: '66', option_b: '77', option_c: '88', option_d: '99', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تسمى سورة النساء الصغرى؟', option_a: 'سورة الطلاق', option_b: 'سورة الممتحنة', option_c: 'سورة المجادلة', option_d: 'سورة الحجرات', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما عدد السور المكية في القرآن؟', option_a: '82', option_b: '86', option_c: '90', option_d: '78', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما عدد السور المدنية في القرآن؟', option_a: '28', option_b: '30', option_c: '32', option_d: '34', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'أي سورة تسمى "سورة بني إسرائيل"؟', option_a: 'سورة الإسراء', option_b: 'سورة يوسف', option_c: 'سورة مريم', option_d: 'سورة طه', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي ذكر فيها اسم الله "الرحمن" أكثر من غيرها؟', option_a: 'سورة الرحمن', option_b: 'سورة الإخلاص', option_c: 'سورة مريم', option_d: 'سورة البقرة', correct_answer: 'C', difficulty: 4 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تبدأ بـ "تبارك"؟', option_a: 'سورة الملك', option_b: 'سورة الواقعة', option_c: 'سورة السجدة', option_d: 'سورة الحديد', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'كم عدد آيات سورة البقرة؟', option_a: '282', option_b: '286', option_c: '290', option_d: '276', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'أين نزلت سورة الفاتحة؟', option_a: 'مكة', option_b: 'المدينة', option_c: 'مكة والمدينة معاً', option_d: 'الطائف', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي أطول آية في القرآن الكريم؟', option_a: 'آية الكرسي', option_b: 'آية الدين (المداينة)', option_c: 'آية المباهلة', option_d: 'آية النور', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'في أي سورة توجد سجدة التلاوة في سورة السجدة؟', option_a: 'سورة السجدة', option_b: 'سورة فصلت', option_c: 'سورة النجم', option_d: 'سورة العلق', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'كم سورة في القرآن تبدأ بـ "الحمد لله"؟', option_a: '4', option_b: '5', option_c: '6', option_d: '7', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تعدل ثلث القرآن؟', option_a: 'سورة الفاتحة', option_b: 'سورة يس', option_c: 'سورة الإخلاص', option_d: 'سورة الملك', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'القرآن الكريم', question_ar: 'كم سورة في القرآن مسماة بأسماء الأنبياء؟', option_a: '6', option_b: '8', option_c: '10', option_d: '12', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تسمى "سورة النعم"؟', option_a: 'سورة النحل', option_b: 'سورة الرحمن', option_c: 'سورة البقرة', option_d: 'سورة الكهف', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'في أي سورة وردت قصة قابيل وهابيل؟', option_a: 'سورة البقرة', option_b: 'سورة المائدة', option_c: 'سورة النساء', option_d: 'سورة الأعراف', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي ختمت باسم نبيين؟', option_a: 'سورة الصافات', option_b: 'سورة الأعلى', option_c: 'سورة الطارق', option_d: 'سورة البلد', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هو عدد أحزاب القرآن؟', option_a: '30', option_b: '40', option_c: '60', option_d: '120', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'القرآن الكريم', question_ar: 'في أي سورة وردت قصة ذي القرنين؟', option_a: 'سورة الكهف', option_b: 'سورة الإسراء', option_c: 'سورة مريم', option_d: 'سورة طه', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي ورد فيها لفظ "الجلالة" أكثر من غيرها؟', option_a: 'سورة البقرة', option_b: 'سورة آل عمران', option_c: 'سورة النساء', option_d: 'سورة المائدة', correct_answer: 'D', difficulty: 4 },
  { categoryName: 'القرآن الكريم', question_ar: 'كم مرة وردت البسملة في القرآن؟', option_a: '113', option_b: '114', option_c: '115', option_d: '112', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'القرآن الكريم', question_ar: 'ما هي السورة التي تعدل ربع القرآن؟', option_a: 'سورة الزلزلة', option_b: 'سورة الكافرون', option_c: 'سورة النصر', option_d: 'سورة الإخلاص', correct_answer: 'B', difficulty: 4 },
  // ====== التفسير ======
  { categoryName: 'التفسير', question_ar: 'ما معنى "الفلق" في سورة الفلق؟', option_a: 'الليل', option_b: 'الصبح', option_c: 'الخير', option_d: 'النور', correct_answer: 'B', difficulty: 2, source: 'تفسير ابن كثير' },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "الم" في بداية سورة البقرة؟', option_a: 'اسم من أسماء الله', option_b: 'حروف مقطعة لا يعلم تأويلها إلا الله', option_c: 'اختصار لكلمات', option_d: 'قسم من الله', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الصراط المستقيم"؟', option_a: 'طريق الجنة', option_b: 'طريق الحق والإسلام', option_c: 'طريق الأنبياء', option_d: 'طريق العلم', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الغاسق إذا وقب"؟', option_a: 'النهار إذا أضاء', option_b: 'الليل إذا دخل', option_c: 'القمر إذا خسف', option_d: 'النجم إذا سقط', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "النفاثات في العقد"؟', option_a: 'الساحرات', option_b: 'المؤمنات', option_c: 'المشركات', option_d: 'المنافقات', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الحمد لله رب العالمين"؟', option_a: 'الشكر لله خالق كل شيء', option_b: 'الثناء على الله رب الخلق أجمعين', option_c: 'تمجيد الله وحده', option_d: 'الدعاء لله', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير قوله تعالى "والتين والزيتون"؟', option_a: 'فاكهتان', option_b: 'جبلان', option_c: 'شجرتان مباركتان', option_d: 'بلدان', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الكوثر"؟', option_a: 'نهر في الجنة', option_b: 'الخير الكثير', option_c: 'شجرة في الجنة', option_d: 'باب من أبواب الجنة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "سورة الإخلاص"؟', option_a: 'توحيد الله وإخلاص العبادة له', option_b: 'قصة الأنبياء', option_c: 'أحكام الصلاة', option_d: 'فضل الصدقة', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الهاوية" في سورة القارعة؟', option_a: 'جبل في النار', option_b: 'النار', option_c: 'بئر في جهنم', option_d: 'واد في جهنم', correct_answer: 'C', difficulty: 4 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير قوله "وعسى أن تكرهوا شيئاً وهو خير لكم"؟', option_a: 'ابتلاء من الله', option_b: 'حكمة الله في الأقدار', option_c: 'اختبار للإيمان', option_d: 'كل ما سبق', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "سجين" في سورة المطففين؟', option_a: 'مكان في الجنة', option_b: 'كتاب الفجار', option_c: 'سجن في الأرض', option_d: 'جبل في النار', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "الطارق"؟', option_a: 'الملاك', option_b: 'النجم الثاقب', option_c: 'الصبح', option_d: 'الذي يطرق ليلاً', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الحاقة"؟', option_a: 'يوم القيامة', option_b: 'الحق الثابت', option_c: 'الساعة', option_d: 'أسماء يوم القيامة', correct_answer: 'D', difficulty: 3 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "الملائكة" في سورة فاطر؟', option_a: 'رسل الله', option_b: 'خلق من نور', option_c: 'لهم أجنحة', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 1 },
  { categoryName: 'التفسير', question_ar: 'ما معنى قوله تعالى "إياك نعبد وإياك نستعين"؟', option_a: 'نخصك بالعبادة ونطلب المعونة', option_b: 'نعبدك ونستغفرك', option_c: 'نطيعك ونرجوك', option_d: 'نشكرك ونحمدك', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "الموقوذة" في سورة المائدة؟', option_a: 'التي تضرب حتى تموت', option_b: 'التي تذبح', option_c: 'التي تموت في الماء', option_d: 'التي تخنق', correct_answer: 'A', difficulty: 4, source: 'تفسير الطبري' },
  { categoryName: 'التفسير', question_ar: 'ما معنى "النسيء" في قوله تعالى "إنما النسيء زيادة في الكفر"؟', option_a: 'النسيان', option_b: 'تأخير الشهور الحرم', option_c: 'زيادة في العبادة', option_d: 'المنسوخ', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "الحجرات" في سورة الحجرات؟', option_a: 'الغرف', option_b: 'الحجارة', option_c: 'القصور', option_d: 'البيوت', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "التكاثر" في سورة التكاثر؟', option_a: 'التكاثر في المال والبنين', option_b: 'كثرة العبادة', option_c: 'كثرة العلم', option_d: 'كثرة الأكل', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الحميم" في القرآن؟', option_a: 'الماء البارد', option_b: 'الماء الحار', option_c: 'الطعام', option_d: 'الشراب', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير قوله تعالى "والسماء والطارق"؟', option_a: 'قسم بالسماء وبالنجم', option_b: 'قسم بالسماء وبالمطر', option_c: 'قسم بالسماء وبالليل', option_d: 'قسم بالسماء وبالنور', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "سدرة المنتهى"؟', option_a: 'شجرة في الجنة', option_b: 'شجرة عندها منتهى علم الملائكة', option_c: 'مكان في النار', option_d: 'جبل في الجنة', correct_answer: 'B', difficulty: 3, source: 'تفسير ابن كثير' },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الكرسي" في آية الكرسي؟', option_a: 'العرش', option_b: 'العلم', option_c: 'مملكة الله', option_d: 'موضع القدمين', correct_answer: 'D', difficulty: 4 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير قوله "ولا تقربوا الزنا" في سورة الإسراء؟', option_a: 'لا تفعلوه', option_b: 'لا تقربوا مقدماته', option_c: 'لا تفكروا فيه', option_d: 'لا تتزوجوا', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الأب" في قوله تعالى "وفاكهة وأبا"؟', option_a: 'الأب الإنسان', option_b: 'الكلأ والمرعى', option_c: 'نوع من الفاكهة', option_d: 'الشجر', correct_answer: 'B', difficulty: 4, source: 'تفسير الطبري' },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "وَالْعَادِيَاتِ ضَبْحاً"؟', option_a: 'الرياح', option_b: 'الخيل', option_c: 'الإبل', option_d: 'الملائكة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الماعون" في سورة الماعون؟', option_a: 'الزكاة', option_b: 'الطعام', option_c: 'ما يتعاون به الناس من المنافع', option_d: 'المال', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "وَالشَّمْسِ وَضُحَاهَا"؟', option_a: 'قسم بالشمس ونهارها', option_b: 'قسم بالشمس وحرها', option_c: 'قسم بالشمس وشروقها', option_d: 'قسم بالشمس وضوئها', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الكتاب" في قوله "ذلك الكتاب لا ريب فيه"؟', option_a: 'التوراة', option_b: 'الإنجيل', option_c: 'القرآن', option_d: 'الزبور', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "الهاكم التكاثر"؟', option_a: 'شغلكم التباهي بالأموال', option_b: 'كثر عبادتكم', option_c: 'كثر علماءكم', option_d: 'كثر نساؤكم', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الزلزلة" في سورة الزلزلة؟', option_a: 'الحركة', option_b: 'الهزة الشديدة', option_c: 'الرياح', option_d: 'الصوت', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "وأنزلنا الحديد فيه بأس شديد"؟', option_a: 'خلق الحديد بقوة', option_b: 'أنزل الحديد من الجنة', option_c: 'علمهم صناعته', option_d: 'أخرج الحديد من الأرض', correct_answer: 'B', difficulty: 4, source: 'تفسير ابن كثير' },
  { categoryName: 'التفسير', question_ar: 'ما معنى "الطور" في قوله "والطور وكتاب مسطور"؟', option_a: 'الجبل', option_b: 'الوادي', option_c: 'البحر', option_d: 'الصحراء', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'التفسير', question_ar: 'ما تفسير "كل نفس بما كسبت رهينة"؟', option_a: 'كل نفس مرهونة بعملها', option_b: 'كل نفس سعيدة', option_c: 'كل نفس محفوظة', option_d: 'كل نفس مخلوقة', correct_answer: 'A', difficulty: 2 },
  // ====== الحديث النبوي ======
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو أول حديث في صحيح البخاري؟', option_a: 'حديث إنما الأعمال بالنيات', option_b: 'حديث الدين النصيحة', option_c: 'حديث بني الإسلام على خمس', option_d: 'حديث من يرد الله به خيرا', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'من صلى الفجر في جماعة فكأنما صلى ...', option_a: 'نصف الليل', option_b: 'الليل كله', option_c: 'قيام ليلة', option_d: 'صلاة ليلة القدر', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'قال النبي ﷺ: "بني الإسلام على خمس" ما هي؟', option_a: 'الصلاة والزكاة والصوم والحج والشهادتان', option_b: 'الصلاة والصدقة والصوم والحج والعمرة', option_c: 'الإيمان والصلاة والزكاة والحج والجهاد', option_d: 'الشهادتان والصلاة والزكاة والصوم والحج', correct_answer: 'D', difficulty: 1 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو الحديث الذي يسمى "أم السنن"؟', option_a: 'حديث إنما الأعمال بالنيات', option_b: 'حديث الدين النصيحة', option_c: 'حديث الحلال بين والحرام بين', option_d: 'حديث من حسن إسلام المرء تركه ما لا يعنيه', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'من يشفع لأمتي يوم القيامة كما ورد في الحديث؟', option_a: 'أبو بكر الصديق', option_b: 'النبي ﷺ', option_c: 'جبرائيل', option_d: 'الملائكة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما معنى "من يرد الله به خيرا يفقهه في الدين"؟', option_a: 'يعطيه مالاً', option_b: 'يفهمه الدين', option_c: 'يرزقه الصحة', option_d: 'يكرمه في الدنيا', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'قال النبي ﷺ: "لا يؤمن أحدكم حتى يحب لأخيه..."', option_a: 'ما يحب لأبيه', option_b: 'ما يحب لنفسه', option_c: 'الخير كله', option_d: 'الجنة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الحديث النبوي', question_ar: 'من أول مصنف في الحديث النبوي؟', option_a: 'الإمام البخاري', option_b: 'الإمام مسلم', option_c: 'ابن ماجه', option_d: 'الإمام مالك في الموطأ', correct_answer: 'D', difficulty: 4 },
  { categoryName: 'الحديث النبوي', question_ar: 'كم عدد أحاديث صحيح البخاري تقريباً؟', option_a: '6000', option_b: '7263', option_c: '5000', option_d: '9000', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما معنى "الحديث القدسي"؟', option_a: 'حديث صحابي عن النبي', option_b: 'حديث يرويه النبي عن ربه', option_c: 'حديث ضعيف', option_d: 'حديث متواتر', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'من روى أكثر الأحاديث عن النبي ﷺ؟', option_a: 'عائشة', option_b: 'أبو هريرة', option_c: 'ابن عباس', option_d: 'أنس بن مالك', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما حكم العمل بالحديث الضعيف؟', option_a: 'يجوز مطلقاً', option_b: 'لا يجوز', option_c: 'يجوز في فضائل الأعمال بشروط', option_d: 'يكره', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'قال النبي ﷺ: "اتق الله حيثما كنت وأتبع السيئة الحسنة..."', option_a: 'تكن من المتقين', option_b: 'تمحها', option_c: 'وخالق الناس بخلق حسن', option_d: 'تدخل الجنة', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'أي من صحاح الحديث يعتبر ثاني أصح كتاب بعد القرآن؟', option_a: 'صحيح البخاري', option_b: 'صحيح مسلم', option_c: 'سنن الترمذي', option_d: 'سنن أبي داود', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو "الإسناد" في الحديث؟', option_a: 'نص الحديث', option_b: 'سلسلة الرواة', option_c: 'حكم الحديث', option_d: 'الجرح والتعديل', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'من هم "السبعة المكثرون" في رواية الحديث؟', option_a: 'سبعة صحابة رووا أكثر الأحاديث', option_b: 'سبعة تابعين', option_c: 'سبعة أئمة', option_d: 'سبعة محدثين', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو "الحديث المتواتر"؟', option_a: 'ما رواه جمع عن جمع', option_b: 'ما رواه واحد', option_c: 'ما رواه اثنان', option_d: 'ما رواه ثلاثة', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو "صحيح مسلم"؟', option_a: 'كتاب جمع فيه الأحاديث الضعيفة', option_b: 'كتاب جمع فيه الأحاديث الصحيحة', option_c: 'كتاب الفقه', option_d: 'كتاب التفسير', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الحديث النبوي', question_ar: 'من هو الإمام مسلم؟', option_a: 'مسلم بن الحجاج النيسابوري', option_b: 'مسلم بن عقيل', option_c: 'مسلم القشيري', option_d: 'مسلم بن الوليد', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هي "السنن الأربعة"؟', option_a: 'أبو داود والترمذي وابن ماجه والنسائي', option_b: 'البخاري ومسلم وأبو داود والترمذي', option_c: 'النسائي وابن ماجه ومالك وأحمد', option_d: 'أبو داود والترمذي والبخاري ومسلم', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'كم عدد أحاديث صحيح مسلم تقريباً؟', option_a: '4000', option_b: '5362', option_c: '6000', option_d: '7275', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'قال النبي ﷺ: "المسلم من سلم المسلمون من ..."', option_a: 'ماله', option_b: 'لسانه ويده', option_c: 'شره', option_d: 'عيبه', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو "الحديث الحسن"؟', option_a: 'ما اتصل سنده بعدل خفيف ضبط', option_b: 'ما صح سنده', option_c: 'ما ضعف سنده', option_d: 'ما اتصل سنده بثقة', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'الحديث النبوي', question_ar: 'من هو صاحب "سنن أبي داود"؟', option_a: 'أبو داود السجستاني', option_b: 'أبو داود الطيالسي', option_c: 'أبو داود الظاهري', option_d: 'أبو داود الموصلي', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'قال النبي ﷺ: "إن الله لا ينظر إلى صوركم ولا أموالكم ولكن ينظر إلى ..."', option_a: 'أعمالكم', option_b: 'قلوبكم وأعمالكم', option_c: 'أخلاقكم', option_d: 'إيمانكم', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو "الحديث المرفوع"؟', option_a: 'ما رفع إلى النبي ﷺ', option_b: 'ما رفع إلى الصحابي', option_c: 'ما رفع إلى التابعي', option_d: 'ما رفع إلى الله', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'قال النبي ﷺ: "من حسن إسلام المرء تركه ما لا يعنيه" رواه ...', option_a: 'البخاري', option_b: 'مسلم', option_c: 'الترمذي', option_d: 'أبو داود', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هي "الموطأ"؟', option_a: 'كتاب للإمام مالك', option_b: 'كتاب للشافعي', option_c: 'كتاب لأحمد', option_d: 'كتاب لأبي حنيفة', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'من هو صاحب "سنن الترمذي"؟', option_a: 'محمد بن عيسى الترمذي', option_b: 'أبو عيسى الترمذي', option_c: 'الحسن بن عيسى', option_d: 'علي بن عيسى', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'قال النبي ﷺ: "الدين النصيحة" لمن؟', option_a: 'لله ورسوله وأئمة المسلمين وعامتهم', option_b: 'لله فقط', option_c: 'للرسول فقط', option_d: 'للأئمة فقط', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو "الحديث الموقوف"؟', option_a: 'ما رفع إلى النبي', option_b: 'ما رفع إلى الصحابي', option_c: 'ما رفع إلى التابعي', option_d: 'ما رفع إلى الله', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الحديث النبوي', question_ar: 'من هو صاحب "مسند أحمد"؟', option_a: 'أحمد بن حنبل', option_b: 'أحمد بن تيمية', option_c: 'أحمد بن شعيب', option_d: 'أحمد بن محمد', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحديث النبوي', question_ar: 'قال النبي ﷺ: "من كان يؤمن بالله واليوم الآخر فليقل خيراً أو..."', option_a: 'ليعمل خيراً', option_b: 'ليصمت', option_c: 'ليسكت', option_d: 'ليدع', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الحديث النبوي', question_ar: 'كم عدد رواة الحديث الذين رووا عن النبي ﷺ؟', option_a: 'أكثر من 100', option_b: 'أكثر من 1000', option_c: 'أكثر من 10000', option_d: 'أكثر من 100000', correct_answer: 'D', difficulty: 4 },
  { categoryName: 'الحديث النبوي', question_ar: 'ما هو "الجرح والتعديل"؟', option_a: 'علم يبحث في أحوال الرواة', option_b: 'نوع من الحديث', option_c: 'فقه الحديث', option_d: 'شرح الحديث', correct_answer: 'A', difficulty: 3 },
  // ====== السيرة النبوية ======
  { categoryName: 'السيرة النبوية', question_ar: 'في أي عام ولد النبي محمد ﷺ؟', option_a: '568م', option_b: '570م', option_c: '571م', option_d: '572م', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'أين ولد النبي محمد ﷺ؟', option_a: 'المدينة المنورة', option_b: 'مكة المكرمة', option_c: 'الطائف', option_d: 'تبوك', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم كان عمر النبي ﷺ عندما نزل عليه الوحي؟', option_a: '30 سنة', option_b: '35 سنة', option_c: '40 سنة', option_d: '45 سنة', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'من هو الملك الذي نزل بالوحي على النبي ﷺ؟', option_a: 'ميكائيل', option_b: 'إسرافيل', option_c: 'جبرائيل', option_d: 'مالك', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'في أي غار نزل الوحي أول مرة؟', option_a: 'غار ثور', option_b: 'غار حراء', option_c: 'غار جبل النور', option_d: 'غار أبي قبيس', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم سنة مكث النبي ﷺ في الدعوة في مكة؟', option_a: '10 سنوات', option_b: '13 سنة', option_c: '15 سنة', option_d: '20 سنة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما اسم أول هجرة في الإسلام؟', option_a: 'الهجرة إلى المدينة', option_b: 'الهجرة إلى الحبشة', option_c: 'الهجرة إلى الطائف', option_d: 'الهجرة إلى الشام', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'من هو أول من آمن من الصبيان؟', option_a: 'عبد الله بن عمر', option_b: 'علي بن أبي طالب', option_c: 'أسامة بن زيد', option_d: 'الحسن بن علي', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما اسم العام الذي ولد فيه النبي ﷺ؟', option_a: 'عام الفيل', option_b: 'عام الحزن', option_c: 'عام الوفود', option_d: 'عام الفتح', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم كان عمر النبي ﷺ عندما توفيت أمه آمنة؟', option_a: '4 سنوات', option_b: '6 سنوات', option_c: '8 سنوات', option_d: '10 سنوات', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'من هي مرضعة النبي ﷺ؟', option_a: 'أم أيمن', option_b: 'حليمة السعدية', option_c: 'ثويبة', option_d: 'سلمى', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'في أي سنة كانت غزوة بدر؟', option_a: '1 هـ', option_b: '2 هـ', option_c: '3 هـ', option_d: '4 هـ', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم عدد المسلمين في غزوة بدر؟', option_a: '500', option_b: '313', option_c: '1000', option_d: '700', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'في أي عام توفي النبي ﷺ؟', option_a: '10 هـ', option_b: '11 هـ', option_c: '12 هـ', option_d: '13 هـ', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'أين دفن النبي محمد ﷺ؟', option_a: 'البقيع', option_b: 'المسجد الحرام', option_c: 'حجرة عائشة في المسجد النبوي', option_d: 'مسجد قباء', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما اسم الرحلة التي قام بها النبي ﷺ من مكة إلى القدس؟', option_a: 'الإسراء', option_b: 'المعراج', option_c: 'الهجرة', option_d: 'العمرة', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما اسم أم النبي محمد ﷺ؟', option_a: 'هند بنت أبي سفيان', option_b: 'آمنة بنت وهب', option_c: 'فاطمة بنت عمرو', option_d: 'خديجة بنت خويلد', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما اسم والد النبي محمد ﷺ؟', option_a: 'أبو طالب', option_b: 'عبد الله بن عبد المطلب', option_c: 'عبد المطلب', option_d: 'أبو لهب', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما اسم جده النبي ﷺ الذي كفله بعد وفاة أمه؟', option_a: 'أبو طالب', option_b: 'عبد المطلب', option_c: 'عبد الله', option_d: 'عمرو بن عائذ', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'من كفل النبي ﷺ بعد وفاة جده؟', option_a: 'أبو بكر', option_b: 'أبو طالب', option_c: 'حمزة', option_d: 'العباس', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم كان عمر النبي ﷺ عندما تزوج خديجة؟', option_a: '20 سنة', option_b: '25 سنة', option_c: '30 سنة', option_d: '35 سنة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم كان عمر خديجة عندما تزوجت النبي ﷺ؟', option_a: '35 سنة', option_b: '40 سنة', option_c: '45 سنة', option_d: '50 سنة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم عدد أبناء النبي ﷺ من خديجة؟', option_a: '4', option_b: '6', option_c: '5', option_d: '7', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما هو عام الحزن؟', option_a: 'العام الذي توفي فيه النبي', option_b: 'العام الذي توفي فيه أبو طالب وخديجة', option_c: 'العام الذي هزم فيه المسلمون', option_d: 'العام الذي ولد فيه النبي', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'من هي أول زوجات النبي ﷺ؟', option_a: 'عائشة', option_b: 'خديجة', option_c: 'سودة', option_d: 'حفصة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم عدد زوجات النبي ﷺ؟', option_a: '9', option_b: '10', option_c: '11', option_d: '12', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'من هو مؤذن النبي ﷺ الأول؟', option_a: 'عمر بن الخطاب', option_b: 'بلال بن رباح', option_c: 'عبد الله بن أم مكتوم', option_d: 'أبو محذورة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم عدد غزوات النبي ﷺ؟', option_a: '19', option_b: '27', option_c: '30', option_d: '12', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما هي أكبر غزوة في الإسلام؟', option_a: 'غزوة بدر', option_b: 'غزوة الخندق', option_c: 'غزوة تبوك', option_d: 'غزوة حنين', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'السيرة النبوية', question_ar: 'في أي سنة كانت غزوة أحد؟', option_a: '2 هـ', option_b: '3 هـ', option_c: '4 هـ', option_d: '5 هـ', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'السيرة النبوية', question_ar: 'من هو الصحابي الذي ردت له الشمس بعد الغروب؟', option_a: 'أبو بكر', option_b: 'عمر', option_c: 'علي بن أبي طالب', option_d: 'عثمان', correct_answer: 'C', difficulty: 4 },
  { categoryName: 'السيرة النبوية', question_ar: 'ما هي معجزة انشقاق القمر؟', option_a: 'انشقاق القمر نصفين', option_b: 'نزول المطر', option_c: 'نبع الماء', option_d: 'تكثير الطعام', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'السيرة النبوية', question_ar: 'في أي سنة كانت بيعة العقبة الأولى؟', option_a: '12 من البعثة', option_b: '10 من البعثة', option_c: '11 من البعثة', option_d: '13 من البعثة', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم عدد من بايعوا النبي في بيعة العقبة الثانية؟', option_a: '70', option_b: '73', option_c: '75', option_d: '80', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'السيرة النبوية', question_ar: 'من هو أول مولود في الإسلام بعد الهجرة؟', option_a: 'الحسن بن علي', option_b: 'عبد الله بن الزبير', option_c: 'عبد الله بن عمر', option_d: 'أسامة بن زيد', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'السيرة النبوية', question_ar: 'كم لبث النبي ﷺ في المدينة بعد الهجرة؟', option_a: '8 سنوات', option_b: '10 سنوات', option_c: '12 سنة', option_d: '13 سنة', correct_answer: 'B', difficulty: 3 },
  // ====== الأنبياء ======
  { categoryName: 'الأنبياء', question_ar: 'كم لبث نوح عليه السلام يدعو قومه؟', option_a: '500 سنة', option_b: '950 سنة', option_c: '800 سنة', option_d: '700 سنة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو أول الأنبياء؟', option_a: 'نوح', option_b: 'آدم', option_c: 'إدريس', option_d: 'إبراهيم', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي ابتلعه الحوت؟', option_a: 'موسى', option_b: 'هارون', option_c: 'يونس', option_d: 'يوسف', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي شق الله له البحر؟', option_a: 'إبراهيم', option_b: 'موسى', option_c: 'عيسى', option_d: 'يوسف', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي ألقي في النار فلم تحرقه؟', option_a: 'إسحاق', option_b: 'إبراهيم', option_c: 'إسماعيل', option_d: 'يعقوب', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي آتاه الله ملكاً عظيماً؟', option_a: 'داود', option_b: 'سليمان', option_c: 'يوسف', option_d: 'محمد', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي كان يعرف بتفسير الأحلام؟', option_a: 'يعقوب', option_b: 'يوسف', option_c: 'إبراهيم', option_d: 'إسحاق', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي بنى السفينة؟', option_a: 'إبراهيم', option_b: 'موسى', option_c: 'نوح', option_d: 'هود', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي كان يعمل حداداً؟', option_a: 'داود', option_b: 'سليمان', option_c: 'أيوب', option_d: 'زكريا', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الأنبياء', question_ar: 'كم عدد الأنبياء والرسل المذكورين في القرآن؟', option_a: '25', option_b: '30', option_c: '20', option_d: '35', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي كان يخاطب قومه باللغة العربية؟', option_a: 'موسى', option_b: 'عيسى', option_c: 'صالح', option_d: 'هود', correct_answer: 'D', difficulty: 3 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي آتاه الله آية الناقة؟', option_a: 'شعيب', option_b: 'صالح', option_c: 'لوط', option_d: 'هود', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي دعا على قومه فقال "رب لا تذر على الأرض من الكافرين دياراً"؟', option_a: 'هود', option_b: 'نوح', option_c: 'صالح', option_d: 'شعيب', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي أيده الله بروح القدس؟', option_a: 'موسى', option_b: 'إبراهيم', option_c: 'عيسى', option_d: 'يحيى', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي قال له الله "وَاصْبِرْ عَلَىٰ مَا أَصَابَكَ"؟', option_a: 'أيوب', option_b: 'محمد', option_c: 'نوح', option_d: 'لقمان', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي كان كليم الله؟', option_a: 'إبراهيم', option_b: 'موسى', option_c: 'محمد', option_d: 'عيسى', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو أول الرسل من الأنبياء؟', option_a: 'آدم', option_b: 'نوح', option_c: 'إبراهيم', option_d: 'محمد', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي أرسل إلى قوم عاد؟', option_a: 'صالح', option_b: 'هود', option_c: 'شعيب', option_d: 'لوط', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي أرسل إلى قوم ثمود؟', option_a: 'هود', option_b: 'صالح', option_c: 'شعيب', option_d: 'نوح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي أرسل إلى قوم لوط؟', option_a: 'هود', option_b: 'صالح', option_c: 'لوط', option_d: 'شعيب', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي أرسل إلى أصحاب مدين؟', option_a: 'شعيب', option_b: 'لوط', option_c: 'نوح', option_d: 'هود', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي أرسل إلى فرعون؟', option_a: 'هارون', option_b: 'موسى', option_c: 'إبراهيم', option_d: 'يوسف', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي رفع إلى السماء؟', option_a: 'إدريس', option_b: 'اليسع', option_c: 'ذو الكفل', option_d: 'إلياس', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي مات ولم يدفن؟', option_a: 'هارون', option_b: 'موسى', option_c: 'يوشع', option_d: 'إلياس', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'الأنبياء', question_ar: 'ما هي معجزة نبي الله عيسى؟', option_a: 'إحياء الموتى', option_b: 'شق البحر', option_c: 'قلب العصا ثعباناً', option_d: 'الناقة', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'ما هي معجزة نبي الله صالح؟', option_a: 'السفينة', option_b: 'الناقة', option_c: 'العصا', option_d: 'النار', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'ما اسم النبي الذي بعثه الله لبني إسرائيل بعد موسى؟', option_a: 'داود', option_b: 'شموئيل', option_c: 'سليمان', option_d: 'يوشع', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'الأنبياء', question_ar: 'كم سنة نام أصحاب الكهف؟', option_a: '309 سنين', option_b: '300 سنة', option_c: '309 أعوام', option_d: '500 سنة', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي قال لقومه "يا قوم اعبدوا الله ما لكم من إله غيره"؟', option_a: 'نوح', option_b: 'هود', option_c: 'صالح', option_d: 'شعيب', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'كم عدد أولاد يعقوب عليه السلام؟', option_a: '10', option_b: '12', option_c: '11', option_d: '13', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي كان أبوه نبياً وجده نبياً؟', option_a: 'يوسف', option_b: 'إسحاق', option_c: 'يعقوب', option_d: 'يحيى', correct_answer: 'D', difficulty: 3 },
  { categoryName: 'الأنبياء', question_ar: 'ما هي معجزة نبي الله موسى في البحر؟', option_a: 'المشي على الماء', option_b: 'شق البحر', option_c: 'إحياء الموتى', option_d: 'إنزال المائدة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي آتاه الله الزبور؟', option_a: 'سليمان', option_b: 'داود', option_c: 'موسى', option_d: 'عيسى', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي أمر بذبح ابنه ورآه في المنام؟', option_a: 'إسحاق', option_b: 'إبراهيم', option_c: 'يعقوب', option_d: 'نوح', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الأنبياء', question_ar: 'من هو النبي الذي كان يغفر الله له كل ذنب؟', option_a: 'آدم', option_b: 'داود', option_c: 'سليمان', option_d: 'يونس', correct_answer: 'B', difficulty: 4 },
  // ====== الصحابة ======
  { categoryName: 'الصحابة', question_ar: 'من هو أول من آمن من الرجال؟', option_a: 'عمر بن الخطاب', option_b: 'أبو بكر الصديق', option_c: 'علي بن أبي طالب', option_d: 'عثمان بن عفان', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الصحابة', question_ar: 'من هو أول من آمن من النساء؟', option_a: 'فاطمة الزهراء', option_b: 'خديجة بنت خويلد', option_c: 'عائشة', option_d: 'أم سلمة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الصحابة', question_ar: 'من هو أول من آمن من الصبيان؟', option_a: 'الحسن بن علي', option_b: 'علي بن أبي طالب', option_c: 'عبد الله بن الزبير', option_d: 'أسامة بن زيد', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الخليفة الراشد الأول؟', option_a: 'عمر بن الخطاب', option_b: 'أبو بكر الصديق', option_c: 'عثمان بن عفان', option_d: 'علي بن أبي طالب', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الصحابة', question_ar: 'من هو الفاروق؟', option_a: 'عثمان بن عفان', option_b: 'عمر بن الخطاب', option_c: 'علي بن أبي طالب', option_d: 'أبو بكر الصديق', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الصحابة', question_ar: 'من هو ذو النورين؟', option_a: 'علي بن أبي طالب', option_b: 'عثمان بن عفان', option_c: 'عمر بن الخطاب', option_d: 'أبو بكر الصديق', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو أسد الله؟', option_a: 'عمر بن الخطاب', option_b: 'حمزة بن عبد المطلب', option_c: 'خالد بن الوليد', option_d: 'علي بن أبي طالب', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو سيد الشهداء؟', option_a: 'خالد بن الوليد', option_b: 'حمزة بن عبد المطلب', option_c: 'عمر بن الخطاب', option_d: 'جعفر بن أبي طالب', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي لقب بـ "الطيار في الجنة"؟', option_a: 'عبد الله بن رواحة', option_b: 'جعفر بن أبي طالب', option_c: 'زيد بن حارثة', option_d: 'خالد بن الوليد', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الجليل الذي كان يسمى "سيف الله المسلول"؟', option_a: 'خالد بن الوليد', option_b: 'سعد بن أبي وقاص', option_c: 'الزبير بن العوام', option_d: 'أبو عبيدة بن الجراح', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي اهتز لموته عرش الرحمن؟', option_a: 'عمر بن الخطاب', option_b: 'سعد بن معاذ', option_c: 'حمزة بن عبد المطلب', option_d: 'مصعب بن عمير', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من هو آخر من توفي من الصحابة؟', option_a: 'أنس بن مالك', option_b: 'أبو الطفيل', option_c: 'جابر بن عبد الله', option_d: 'عبد الله بن عمر', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'الصحابة', question_ar: 'من هي الملقبة بـ "الحوراء"؟', option_a: 'عائشة', option_b: 'فاطمة الزهراء', option_c: 'خديجة', option_d: 'مريم', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من كان كاتب الوحي للنبي ﷺ؟', option_a: 'أبو بكر الصديق', option_b: 'زيد بن ثابت', option_c: 'علي بن أبي طالب', option_d: 'عبد الله بن مسعود', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي جمع القرآن في مصحف واحد؟', option_a: 'أبو بكر الصديق', option_b: 'عمر بن الخطاب', option_c: 'زيد بن ثابت', option_d: 'عثمان بن عفان', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الملقب بـ "أمين الأمة"؟', option_a: 'أبو عبيدة بن الجراح', option_b: 'خالد بن الوليد', option_c: 'سعد بن أبي وقاص', option_d: 'عبد الله بن مسعود', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الملقب بـ "الزاهد"؟', option_a: 'أبو ذر الغفاري', option_b: 'سلمان الفارسي', option_c: 'صهيب الرومي', option_d: 'بلال بن رباح', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي بايع على أن لا يسأل الناس شيئاً؟', option_a: 'أبو ذر الغفاري', option_b: 'ثوبان', option_c: 'عبد الله بن معقل', option_d: 'عوف بن مالك', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'الصحابة', question_ar: 'من هي "ذات النطاقين"؟', option_a: 'عائشة', option_b: 'أسماء بنت أبي بكر', option_c: 'فاطمة', option_d: 'خديجة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي كان يسمى "الباحث عن الحق"؟', option_a: 'سلمان الفارسي', option_b: 'صهيب الرومي', option_c: 'بلال بن رباح', option_d: 'عمار بن ياسر', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي قال له النبي ﷺ "هذا خير رجالنا"؟', option_a: 'أبو بكر', option_b: 'خالد بن الوليد', option_c: 'أبو عبيدة بن الجراح', option_d: 'عمر بن الخطاب', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي كان مع النبي في الغار؟', option_a: 'عمر', option_b: 'أبو بكر', option_c: 'علي', option_d: 'عثمان', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الصحابة', question_ar: 'من هو أحد العشرة المبشرين بالجنة؟', option_a: 'خالد بن الوليد', option_b: 'سعد بن أبي وقاص', option_c: 'عمرو بن العاص', option_d: 'معاوية بن أبي سفيان', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الملقب بـ "الصديق"؟', option_a: 'عمر', option_b: 'أبو بكر', option_c: 'عثمان', option_d: 'علي', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الصحابة', question_ar: 'من هي أول شهيدة في الإسلام؟', option_a: 'فاطمة', option_b: 'سمية بنت خياط', option_c: 'خديجة', option_d: 'أم سلمة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي كان يقال له "ترجمان القرآن"؟', option_a: 'زيد بن ثابت', option_b: 'عبد الله بن عباس', option_c: 'عبد الله بن مسعود', option_d: 'أبي بن كعب', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الملقب بـ "الأسد الجريء"؟', option_a: 'علي بن أبي طالب', option_b: 'عمر بن الخطاب', option_c: 'خالد بن الوليد', option_d: 'الزبير بن العوام', correct_answer: 'D', difficulty: 4 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الملقب بـ "قارئ القرآن" الذي كان يقرأ للنبي؟', option_a: 'عبد الله بن مسعود', option_b: 'أبي بن كعب', option_c: 'زيد بن ثابت', option_d: 'عبد الله بن عباس', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي كان يسمى "حاجب النبي"؟', option_a: 'أنس بن مالك', option_b: 'أبو مسعود البدري', option_c: 'أنس بن النضر', option_d: 'أبو هريرة', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي كان رسول النبي إلى كسرى؟', option_a: 'عبد الله بن حذافة', option_b: 'دحية الكلبي', option_c: 'العلاء بن الحضرمي', option_d: 'عمرو بن العاص', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي قتل أبا جهل؟', option_a: 'خالد بن الوليد', option_b: 'معاذ بن عمرو بن الجموح', option_c: 'سعد بن أبي وقاص', option_d: 'عبد الله بن مسعود', correct_answer: 'D', difficulty: 4 },
  { categoryName: 'الصحابة', question_ar: 'في أي غزوة استشهد حمزة بن عبد المطلب؟', option_a: 'بدر', option_b: 'أحد', option_c: 'الخندق', option_d: 'تبوك', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الصحابة', question_ar: 'من هو الصحابي الذي كان رديف النبي ﷺ في هجرته؟', option_a: 'علي بن أبي طالب', option_b: 'أبو بكر الصديق', option_c: 'عبد الله بن أبي بكر', option_d: 'عامر بن فهيرة', correct_answer: 'C', difficulty: 4 },
  { categoryName: 'الصحابة', question_ar: 'من هو أول من جهر بالقرآن في مكة؟', option_a: 'أبو بكر', option_b: 'عمر', option_c: 'عبد الله بن مسعود', option_d: 'خالد بن الوليد', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'الصحابة', question_ar: 'من هي زوجة النبي التي كانت تسمى "أم المساكين"؟', option_a: 'عائشة', option_b: 'زينب بنت خزيمة', option_c: 'أم سلمة', option_d: 'حفصة', correct_answer: 'B', difficulty: 4 },
  // ====== التاريخ الإسلامي ======
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي سنة كانت غزوة أحد؟', option_a: '2 هـ', option_b: '3 هـ', option_c: '4 هـ', option_d: '5 هـ', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي سنة كانت غزوة الخندق؟', option_a: '3 هـ', option_b: '4 هـ', option_c: '5 هـ', option_d: '6 هـ', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي سنة تم فتح مكة؟', option_a: '6 هـ', option_b: '7 هـ', option_c: '8 هـ', option_d: '9 هـ', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو مؤسس الدولة الأموية؟', option_a: 'عبد الملك بن مروان', option_b: 'معاوية بن أبي سفيان', option_c: 'الوليد بن عبد الملك', option_d: 'عمر بن عبد العزيز', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام كانت معركة حطين؟', option_a: '583 هـ', option_b: '584 هـ', option_c: '585 هـ', option_d: '583 هـ', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو القائد الذي فتح الأندلس؟', option_a: 'طارق بن زياد', option_b: 'موسى بن نصير', option_c: 'عبد الرحمن الداخل', option_d: 'الحجاج بن يوسف', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو الخليفة العباسي الأول؟', option_a: 'أبو جعفر المنصور', option_b: 'أبو العباس السفاح', option_c: 'هارون الرشيد', option_d: 'المأمون', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام سقطت الأندلس؟', option_a: '897 هـ', option_b: '898 هـ', option_c: '899 هـ', option_d: '900 هـ', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو القائد الذي فتح القدس في العصر الإسلامي الأول؟', option_a: 'صلاح الدين الأيوبي', option_b: 'عمر بن الخطاب', option_c: 'خالد بن الوليد', option_d: 'أبو عبيدة بن الجراح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو صلاح الدين الأيوبي؟', option_a: 'خليفة عباسي', option_b: 'قائد أموي', option_c: 'قائد أيوبي حرر القدس', option_d: 'والي من قبل الفاطميين', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام كانت معركة القادسية؟', option_a: '14 هـ', option_b: '15 هـ', option_c: '16 هـ', option_d: '18 هـ', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو قائد معركة القادسية؟', option_a: 'خالد بن الوليد', option_b: 'سعد بن أبي وقاص', option_c: 'أبو عبيدة بن الجراح', option_d: 'القعقاع بن عمرو', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'ما هي أول عاصمة للدولة الإسلامية بعد الهجرة؟', option_a: 'مكة', option_b: 'المدينة المنورة', option_c: 'دمشق', option_d: 'بغداد', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام هاجر النبي ﷺ إلى المدينة؟', option_a: '620م', option_b: '621م', option_c: '622م', option_d: '623م', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو الخليفة الذي أمر ببناء قبة الصخرة؟', option_a: 'معاوية بن أبي سفيان', option_b: 'عبد الملك بن مروان', option_c: 'الوليد بن عبد الملك', option_d: 'عمر بن عبد العزيز', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'ما هي أول غزوة في الإسلام؟', option_a: 'غزوة بدر', option_b: 'غزوة الأبواء (ودان)', option_c: 'غزوة أحد', option_d: 'غزوة بواط', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو مؤسس الدولة العباسية؟', option_a: 'أبو جعفر المنصور', option_b: 'أبو العباس السفاح', option_c: 'محمد بن علي العباسي', option_d: 'عبد الله بن العباس', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام كانت معركة اليرموك؟', option_a: '13 هـ', option_b: '15 هـ', option_c: '16 هـ', option_d: '12 هـ', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو قائد معركة اليرموك؟', option_a: 'خالد بن الوليد', option_b: 'أبو عبيدة بن الجراح', option_c: 'سعد بن أبي وقاص', option_d: 'الزبير بن العوام', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو آخر الخلفاء الراشدين؟', option_a: 'عثمان بن عفان', option_b: 'علي بن أبي طالب', option_c: 'عمر بن الخطاب', option_d: 'الحسن بن علي', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام كانت فتح مصر في الإسلام؟', option_a: '18 هـ', option_b: '20 هـ', option_c: '21 هـ', option_d: '19 هـ', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو قائد فتح مصر؟', option_a: 'خالد بن الوليد', option_b: 'عمرو بن العاص', option_c: 'سعد بن أبي وقاص', option_d: 'الزبير بن العوام', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'ما هي عاصمة الخلافة العباسية؟', option_a: 'دمشق', option_b: 'بغداد', option_c: 'الكوفة', option_d: 'البصرة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'ما هي عاصمة الخلافة الأموية؟', option_a: 'بغداد', option_b: 'دمشق', option_c: 'القاهرة', option_d: 'المدينة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام كانت فتح بلاد فارس؟', option_a: '21 هـ', option_b: '23 هـ', option_c: '20 هـ', option_d: '25 هـ', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو الخليفة الذي يعرف بـ "خامس الخلفاء الراشدين"؟', option_a: 'عمر بن عبد العزيز', option_b: 'الحسن بن علي', option_c: 'معاوية بن أبي سفيان', option_d: 'عبد الله بن الزبير', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'ما اسم المعركة التي انتصر فيها صلاح الدين على الصليبيين؟', option_a: 'معركة عين جالوت', option_b: 'معركة حطين', option_c: 'معركة المنصورة', option_d: 'معركة الزلاقة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو السلطان المملوكي الذي هزم المغول في عين جالوت؟', option_a: 'الظاهر بيبرس', option_b: 'قطز', option_c: 'المنصور قلاوون', option_d: 'الناصر محمد', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو القائد العثماني الذي فتح القسطنطينية؟', option_a: 'بايزيد الأول', option_b: 'محمد الفاتح', option_c: 'سليمان القانوني', option_d: 'أورخان غازي', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام فتحت القسطنطينية؟', option_a: '1452', option_b: '1453', option_c: '1454', option_d: '1455', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو مؤسس الدولة الفاطمية؟', option_a: 'عبد الله المهدي', option_b: 'المعز لدين الله', option_c: 'الحاكم بأمر الله', option_d: 'العزيز بالله', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'في أي عام كانت معركة الزلاقة؟', option_a: '479 هـ', option_b: '480 هـ', option_c: '481 هـ', option_d: '478 هـ', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو القائد الأموي الذي فتح السند؟', option_a: 'الوليد بن عبد الملك', option_b: 'محمد بن القاسم الثقفي', option_c: 'الحجاج بن يوسف', option_d: 'قتيبة بن مسلم', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'التاريخ الإسلامي', question_ar: 'من هو القائد المسلم الذي فتح بلاد ما وراء النهر؟', option_a: 'محمد بن القاسم', option_b: 'قتيبة بن مسلم', option_c: 'موسى بن نصير', option_d: 'طارق بن زياد', correct_answer: 'B', difficulty: 3 },
  // ====== الفقه ======
  { categoryName: 'الفقه', question_ar: 'ما حكم أكل لحم الخنزير في الإسلام؟', option_a: 'مكروه', option_b: 'حرام', option_c: 'حلال', option_d: 'مباح', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'كم عدد أركان الصلاة؟', option_a: '12', option_b: '14', option_c: '17', option_d: '13', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الفقه', question_ar: 'ما هي شروط صحة الصلاة؟', option_a: 'الوضوء والوقت والقبلة والنية', option_b: 'الطهارة والنية والوقت والقبلة', option_c: 'الإيمان والوضوء والوقت', option_d: 'النية والطهارة فقط', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما حكم شرب الخمر في الإسلام؟', option_a: 'مكروه', option_b: 'حرام', option_c: 'حلال بقلة', option_d: 'مباح', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'ما مقدار زكاة المال؟', option_a: '5%', option_b: '10%', option_c: '2.5%', option_d: '1%', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'من هم الذين تجب عليهم الزكاة؟', option_a: 'الفقراء فقط', option_b: 'الأغنياء الذين يملكون النصاب', option_c: 'كل المسلمين', option_d: 'الرجال فقط', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما حكم صلاة الجمعة؟', option_a: 'سنة', option_b: 'فرض عين', option_c: 'فرض كفاية', option_d: 'مستحبة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'ما هي مبطلات الصيام؟', option_a: 'الأكل والشرب والجماع عمداً', option_b: 'النوم', option_c: 'السفر', option_d: 'المرض', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما حكم الربا في الإسلام؟', option_a: 'مكروه', option_b: 'حرام', option_c: 'حلال', option_d: 'مباح بشروط', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'كم عدد ركعات صلاة الفجر؟', option_a: 'ركعتان', option_b: 'ثلاث', option_c: 'أربع', option_d: 'واحدة', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'ما حكم التيمم؟', option_a: 'بديل عن الوضوء عند فقد الماء', option_b: 'سنة فقط', option_c: 'واجب عند كل صلاة', option_d: 'لا يجوز إلا في السفر', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما هي عدد الطواف حول الكعبة؟', option_a: '5 أشواط', option_b: '7 أشواط', option_c: '8 أشواط', option_d: '6 أشواط', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'ما هو الحد الأدنى للنصاب في زكاة الذهب؟', option_a: '85 جراماً', option_b: '100 جرام', option_c: '50 جراماً', option_d: '200 جرام', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الفقه', question_ar: 'هل يجوز الجمع بين الصلاتين في السفر؟', option_a: 'نعم يجوز', option_b: 'لا يجوز', option_c: 'مكروه', option_d: 'حرام', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما هي شروط الحجاب الشرعي؟', option_a: 'تغطية العورة وعدم الزينة', option_b: 'تغطية الوجه فقط', option_c: 'لبس الأسود فقط', option_d: 'تغطية الرأس مع كشف الوجه والكفين', correct_answer: 'D', difficulty: 3 },
  { categoryName: 'الفقه', question_ar: 'ما حكم أكل لحم الخيل؟', option_a: 'حرام', option_b: 'مكروه', option_c: 'حلال', option_d: 'مباح', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'الفقه', question_ar: 'كم عدد ركعات صلاة الظهر؟', option_a: 'أربع ركعات', option_b: 'ثلاث ركعات', option_c: 'ركعتان', option_d: 'خمس ركعات', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'ما حكم صلاة الوتر؟', option_a: 'فرض', option_b: 'سنة مؤكدة', option_c: 'واجبة', option_d: 'مستحبة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما حكم الغش في الامتحان؟', option_a: 'مباح', option_b: 'حرام', option_c: 'مكروه', option_d: 'جائز للضرورة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'ما حكم الأضحية في عيد الأضحى؟', option_a: 'فرض', option_b: 'سنة مؤكدة', option_c: 'واجبة', option_d: 'مستحبة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما هي أركان الوضوء؟', option_a: 'غسل الوجه واليدين ومسح الرأس وغسل الرجلين', option_b: 'غسل اليدين والرجلين فقط', option_c: 'غسل الوجه واليدين فقط', option_d: 'الوضوء مرة واحدة', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما حكم قص الأظافر للرجل في العشر الأوائل من ذي الحجة لمن أراد الأضحية؟', option_a: 'حرام', option_b: 'مكروه', option_c: 'سنة', option_d: 'مباح', correct_answer: 'B', difficulty: 4 },
  { categoryName: 'الفقه', question_ar: 'ما حكم نكاح المتعة؟', option_a: 'جائز', option_b: 'حرام', option_c: 'مكروه', option_d: 'مباح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما هي عدة المطلقة المدخول بها؟', option_a: 'شهر واحد', option_b: 'ثلاث حيض', option_c: 'أربعة أشهر وعشر', option_d: 'سنة كاملة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الفقه', question_ar: 'ما حكم أكل الميتة في حالة الضرورة؟', option_a: 'حرام مطلقاً', option_b: 'حلال بقدر الضرورة', option_c: 'مكروه', option_d: 'مباح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما هي صلاة الاستخارة؟', option_a: 'صلاة لطلب الخير في الأمور', option_b: 'صلاة التوبة', option_c: 'صلاة الحاجة', option_d: 'صلاة الشكر', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'كم عدد ركعات صلاة العشاء؟', option_a: 'أربع ركعات', option_b: 'ثلاث ركعات', option_c: 'خمس ركعات', option_d: 'ركعتان', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الفقه', question_ar: 'ما حكم لبس الذهب للرجال؟', option_a: 'حلال', option_b: 'حرام', option_c: 'مكروه', option_d: 'مباح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما هي شروط صحة البيع في الإسلام؟', option_a: 'التراضي والعقد والمحل', option_b: 'العقد والثمن', option_c: 'التراضي فقط', option_d: 'الكتابة والشهود', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الفقه', question_ar: 'ما حكم الإسراف في الماء حتى ولو كنت على نهر جار؟', option_a: 'مباح', option_b: 'حرام', option_c: 'مكروه', option_d: 'جائز', correct_answer: 'C', difficulty: 3, source: 'حديث نبوي' },
  { categoryName: 'الفقه', question_ar: 'ما هي نواقض الوضوء؟', option_a: 'الخارج من السبيلين والنوم والمس', option_b: 'الأكل والشرب', option_c: 'الكلام', option_d: 'النظر', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما حكم الرضاع في الإسلام؟', option_a: 'لا يؤثر', option_b: 'يحرم ما يحرم من النسب', option_c: 'مكروه', option_d: 'يبطل الوضوء', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما هي صلاة الكسوف؟', option_a: 'صلاة عند كسوف الشمس', option_b: 'صلاة عند المطر', option_c: 'صلاة عند الزلزال', option_d: 'صلاة عند الريح', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الفقه', question_ar: 'ما حكم اليمين الغموس؟', option_a: 'تكفر بالكفارة', option_b: 'من الكبائر', option_c: 'مباحة', option_d: 'مكروهة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الفقه', question_ar: 'كم عدد ركعات صلاة التراويح عند الحنفية؟', option_a: '8 ركعات', option_b: '20 ركعة', option_c: '36 ركعة', option_d: '12 ركعة', correct_answer: 'B', difficulty: 3 },
  // ====== العقيدة ======
  { categoryName: 'العقيدة', question_ar: 'ما هو أول واجب على المكلف؟', option_a: 'الصلاة', option_b: 'الشهادتان', option_c: 'الصوم', option_d: 'الحج', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'كم عدد أركان الإيمان؟', option_a: '5', option_b: '6', option_c: '7', option_d: '4', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'كم عدد أركان الإسلام؟', option_a: '5', option_b: '6', option_c: '7', option_d: '4', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'ما هو الإحسان؟', option_a: 'فعل الخيرات', option_b: 'أن تعبد الله كأنك تراه', option_c: 'الإخلاص في العمل', option_d: 'بر الوالدين', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'من أول من سجد من الملائكة لآدم؟', option_a: 'ميكائيل', option_b: 'إبليس', option_c: 'جبرائيل', option_d: 'جميع الملائكة', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما هو الشرك بالله؟', option_a: 'الكفر بالله', option_b: 'صرف العبادة لغير الله', option_c: 'النفاق', option_d: 'ترك الصلاة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما هي أعظم آية في القرآن؟', option_a: 'آية الكرسي', option_b: 'آخر آية من البقرة', option_c: 'أول آية من آل عمران', option_d: 'آية النور', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'من هو أول الرسل؟', option_a: 'نوح', option_b: 'إبراهيم', option_c: 'آدم', option_d: 'محمد', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما معنى "لا إله إلا الله"؟', option_a: 'لا خالق إلا الله', option_b: 'لا معبود بحق إلا الله', option_c: 'لا رازق إلا الله', option_d: 'لا رب إلا الله', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'ما هو القدر؟', option_a: 'علم الله المسبق بما سيكون', option_b: 'ما يكتبه الله للإنسان', option_c: 'تقدير الله لمقادير الخلق', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما هي الصراط؟', option_a: 'جسر في الجنة', option_b: 'جسر على جهنم', option_c: 'جسر على النار إلى الجنة', option_d: 'باب الجنة', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'كم عدد أسماء الله الحسنى؟', option_a: '100', option_b: '99', option_c: '90', option_d: '1000', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'من هو النبي الخاتم؟', option_a: 'عيسى', option_b: 'موسى', option_c: 'محمد ﷺ', option_d: 'إبراهيم', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'ما هو الميزان يوم القيامة؟', option_a: 'ميزان حسنات وسيئات', option_b: 'ميزان حقيقي', option_c: 'ميزان الأعمال', option_d: 'ميزان العدل', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'أين يكون المسلمون يوم القيامة؟', option_a: 'في أرض المحشر', option_b: 'في الجنة', option_c: 'في النار', option_d: 'في البرزخ', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما هي الكبائر من الذنوب؟', option_a: 'الذنوب التي توجب النار', option_b: 'الذنوب الصغيرة', option_c: 'الذنوب التي تكفر بالتوبة', option_d: 'الذنوب التي تغفر بالصلاة', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما معنى الإيمان بالملائكة؟', option_a: 'التصديق بوجودهم', option_b: 'عبادتهم', option_c: 'دعائهم', option_d: 'التقرب إليهم', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'ما هو يوم القيامة؟', option_a: 'يوم يبعث الناس فيه', option_b: 'يوم النهاية', option_c: 'يوم الحساب', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'ما هي البرزخ؟', option_a: 'الحياة بين الدنيا والآخرة', option_b: 'جسر', option_c: 'مكان في الجنة', option_d: 'باب النار', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'كم عدد الكتب السماوية التي ذكرت في القرآن؟', option_a: '3', option_b: '4', option_c: '5', option_d: '6', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'العقيدة', question_ar: 'ما اسم الصحف التي أنزلت على إبراهيم؟', option_a: 'صحف إبراهيم', option_b: 'التوراة', option_c: 'الزبور', option_d: 'الفرقان', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'العقيدة', question_ar: 'ما معنى الإيمان بالله؟', option_a: 'التصديق بوجود الله وتوحيده', option_b: 'الإيمان بالرسل فقط', option_c: 'الإيمان باليوم الآخر', option_d: 'الإيمان بالقدر', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'العقيدة', question_ar: 'ما هو النفاق الأكبر؟', option_a: 'إظهار الإسلام وإبطان الكفر', option_b: 'الكذب', option_c: 'الخيانة', option_d: 'الرياء', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما حكم من جحد وجوب الصلاة؟', option_a: 'عاص', option_b: 'كافر', option_c: 'فاسق', option_d: 'مبتدع', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما هو الحوض يوم القيامة؟', option_a: 'نهر في الجنة', option_b: 'حوض للنبي ﷺ يشرب منه المؤمنون', option_c: 'باب من أبواب الجنة', option_d: 'نور يوم القيامة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'العقيدة', question_ar: 'من هم أهل البدع؟', option_a: 'الذين يخالفون السنة', option_b: 'الذين يصلون', option_c: 'الذين يصومون', option_d: 'الذين يحجون', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'العقيدة', question_ar: 'ما هي "الشفاعة العظمى"؟', option_a: 'شفاعة النبي لأمته يوم القيامة', option_b: 'شفاعة الملائكة', option_c: 'شفاعة الصالحين', option_d: 'شفاعة الشهداء', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما هي أول فتنة في الإسلام؟', option_a: 'فتنة مقتل عثمان', option_b: 'فتنة مسيلمة', option_c: 'فتنة طالوت', option_d: 'فتنة عبادة الأوثان', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'العقيدة', question_ar: 'ما معنى "السحر" في العقيدة الإسلامية؟', option_a: 'حق وله حقيقة', option_b: 'باطل لا حقيقة له', option_c: 'خيال', option_d: 'وهم', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'العقيدة', question_ar: 'ما هي "النبوات" في العقيدة؟', option_a: 'الإيمان بالأنبياء والرسل', option_b: 'الإيمان بالكتب', option_c: 'الإيمان بالملائكة', option_d: 'الإيمان بالقدر', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'من هو أول من قال "ربي الله" من البشر؟', option_a: 'محمد', option_b: 'إبراهيم', option_c: 'آدم', option_d: 'نوح', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'العقيدة', question_ar: 'ما هي أقسام التوحيد؟', option_a: 'توحيد الربوبية والألوهية والأسماء والصفات', option_b: 'توحيد الإيمان والإسلام', option_c: 'توحيد العلم والعمل', option_d: 'توحيد الظاهر والباطن', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'العقيدة', question_ar: 'ما هو معنى "الصمد" من أسماء الله؟', option_a: 'الذي يصمد إليه الخلق', option_b: 'الذي لا يأكل', option_c: 'الذي لا يشرب', option_d: 'الذي ينام', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'العقيدة', question_ar: 'ما هو "اللوح المحفوظ"؟', option_a: 'كتاب فيه أعمال العباد', option_b: 'كتاب فيه مقادير الخلق', option_c: 'كتاب القرآن', option_d: 'كتاب الحسنات', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'العقيدة', question_ar: 'من هو إمام أهل السنة في العقيدة؟', option_a: 'أبو الحسن الأشعري', option_b: 'أبو حنيفة', option_c: 'مالك', option_d: 'الشافعي', correct_answer: 'A', difficulty: 4 },
  // ====== الآداب الإسلامية ======
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول إذا عطس أحد؟', option_a: 'بارك الله فيك', option_b: 'يرحمكم الله', option_c: 'الحمد لله', option_d: 'شفاك الله', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما هو دعاء دخول المنزل؟', option_a: 'بسم الله ولجنا وبسم الله خرجنا', option_b: 'اللهم افتح لي أبواب رحمتك', option_c: 'رب أدخلني مدخل صدق', option_d: 'الحمد لله الذي عافاني', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند رؤية من ابتلي بمصيبة؟', option_a: 'لا حول ولا قوة إلا بالله', option_b: 'الحمد لله الذي عافاني مما ابتلاك به', option_c: 'إنا لله وإنا إليه راجعون', option_d: 'سبحان الله', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم الغيبة في الإسلام؟', option_a: 'مباحة', option_b: 'مكروهة', option_c: 'حرام', option_d: 'مباحة بين الأصدقاء', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند دخول الخلاء؟', option_a: 'اللهم إني أعوذ بك من الخبث والخبائث', option_b: 'بسم الله', option_c: 'الحمد لله', option_d: 'لا إله إلا الله', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند الخروج من الخلاء؟', option_a: 'بسم الله', option_b: 'غفرانك', option_c: 'الحمد لله الذي أذهب عني الأذى وعافاني', option_d: 'لا إله إلا الله', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما هو حكم الكذب في الإسلام؟', option_a: 'مباح للمزاح', option_b: 'حرام إلا في حالات محددة', option_c: 'مكروه', option_d: 'مباح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا يقول المسلم عند المصيبة؟', option_a: 'لا حول ولا قوة إلا بالله', option_b: 'إنا لله وإنا إليه راجعون', option_c: 'الحمد لله على كل حال', option_d: 'اللهم أجرني في مصيبتي', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم سب الدين أو المقدسات؟', option_a: 'ذنب كبير', option_b: 'كفر', option_c: 'معصية', option_d: 'مكروه', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند النوم؟', option_a: 'باسمك ربي وضعت جنبي وبك أرفعه', option_b: 'اللهم إني أعوذ بك من عذاب القبر', option_c: 'سبحان الله 33 مرة', option_d: 'لا إله إلا الله', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما هو حكم التبذير والإسراف؟', option_a: 'مباح', option_b: 'حرام', option_c: 'مكروه', option_d: 'سنة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'من هم الجيران الذين أوصى بهم النبي ﷺ؟', option_a: 'الجار القريب', option_b: 'الجار البعيد', option_c: 'الجار المسلم والكافر', option_d: 'الجار المسلم فقط', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم قطع الرحم؟', option_a: 'مباح', option_b: 'حرام وكبيرة من الكبائر', option_c: 'مكروه', option_d: 'مباح إذا أساء الأقارب', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند الأكل؟', option_a: 'الحمد لله', option_b: 'بسم الله', option_c: 'بسم الله الرحمن الرحيم', option_d: 'اللهم بارك لنا فيه', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول بعد الفراغ من الأكل؟', option_a: 'بسم الله', option_b: 'الحمد لله الذي أطعمني وسقاني', option_c: 'شكراً لله', option_d: 'اللهم زدنا', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم النميمة؟', option_a: 'مباحة', option_b: 'حرام', option_c: 'مكروهة', option_d: 'مباحة بين الأصدقاء', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما هو دعاء السفر؟', option_a: 'اللهم إنا نسألك في سفرنا هذا البر والتقوى', option_b: 'بسم الله', option_c: 'الحمد لله', option_d: 'لا إله إلا الله', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند رؤية الهلال؟', option_a: 'الله أكبر', option_b: 'اللهم أهله علينا بالأمن والإيمان', option_c: 'بسم الله', option_d: 'سبحان الله', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم التكبر في الإسلام؟', option_a: 'مباح', option_b: 'حرام', option_c: 'مكروه', option_d: 'سنة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم رد السلام؟', option_a: 'سنة', option_b: 'واجب', option_c: 'مستحب', option_d: 'مباح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند الصباح؟', option_a: 'اللهم بك أصبحنا', option_b: 'بسم الله', option_c: 'الحمد لله', option_d: 'لا إله إلا الله', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما هو حكم اللعن في الإسلام؟', option_a: 'مباح', option_b: 'لا ينبغي للمؤمن أن يكون لعاناً', option_c: 'سنة', option_d: 'مستحب', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم الاستهزاء بالدين؟', option_a: 'ذنب', option_b: 'كفر', option_c: 'معصية', option_d: 'مكروه', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند ركوب الدابة أو السيارة؟', option_a: 'سبحان الذي سخر لنا هذا', option_b: 'بسم الله', option_c: 'الله أكبر', option_d: 'الحمد لله', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم التباهي والتفاخر؟', option_a: 'مباح', option_b: 'مكروه', option_c: 'حرام', option_d: 'مستحب', correct_answer: 'C', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما هو أدب العطاس؟', option_a: 'يقول الحمد لله', option_b: 'يقول يرحمكم الله', option_c: 'يسكت', option_d: 'يضحك', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا يقول من يشمّت العاطس؟', option_a: 'يرحمكم الله', option_b: 'الحمد لله', option_c: 'بارك الله فيك', option_d: 'شفاك الله', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم مجالس الغيبة والنميمة؟', option_a: 'يجوز حضورها', option_b: 'يجب إنكارها أو الخروج منها', option_c: 'مباحة', option_d: 'مستحبة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم التسمية عند الوضوء؟', option_a: 'فرض', option_b: 'سنة', option_c: 'واجب', option_d: 'مباح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'من أولى الناس بحسن الصحبة؟', option_a: 'الأب', option_b: 'الأم', option_c: 'الأخ', option_d: 'الزوج', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم ترويع المسلم؟', option_a: 'مباح', option_b: 'حرام', option_c: 'مكروه', option_d: 'جائز', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما هو أدب الاستئذان؟', option_a: 'يدخل بلا استئذان', option_b: 'يستأذن ثلاثاً', option_c: 'يطرق الباب بقوة', option_d: 'ينادي بصوت عال', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما حكم هجر المسلم لأخيه فوق ثلاث؟', option_a: 'لا بأس به', option_b: 'لا يحل', option_c: 'مباح', option_d: 'سنة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ما هي صلة الرحم؟', option_a: 'زيارة الأقارب والإحسان إليهم', option_b: 'الصدقة فقط', option_c: 'الصلاة فقط', option_d: 'السلام فقط', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الآداب الإسلامية', question_ar: 'ماذا نقول عند الخروج من المنزل؟', option_a: 'بسم الله توكلت على الله', option_b: 'اللهم إني أعوذ بك', option_c: 'رب أدخلني', option_d: 'الحمد لله', correct_answer: 'A', difficulty: 2 },
  // ====== رمضان ======
  { categoryName: 'رمضان', question_ar: 'كم يوماً يصوم المسلم في رمضان؟', option_a: '28 يوماً', option_b: '30 يوماً', option_c: '29 أو 30 يوماً', option_d: '31 يوماً', correct_answer: 'C', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'في أي سنة فرض صيام رمضان؟', option_a: '1 هـ', option_b: '2 هـ', option_c: '3 هـ', option_d: '4 هـ', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما هي ليلة القدر؟', option_a: 'ليلة في رمضان', option_b: 'أفضل من ألف شهر', option_c: 'ليلة يغفر فيها الذنوب', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'في أي العشر الأواخر من رمضان تطلب ليلة القدر؟', option_a: 'العشر الأوائل', option_b: 'العشر الأواخر', option_c: 'العشر الأوسط', option_d: 'الأيام البيض', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'ما هي صلاة القيام في رمضان؟', option_a: 'صلاة التراويح', option_b: 'صلاة التهجد', option_c: 'صلاة الليل', option_d: 'جميع ما سبق', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما حكم الإفطار في رمضان بدون عذر؟', option_a: 'مكروه', option_b: 'حرام وكبيرة من الكبائر', option_c: 'مباح', option_d: 'مباح مع القضاء', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'ما هو حكم السحور؟', option_a: 'فرض', option_b: 'سنة مؤكدة', option_c: 'مستحب', option_d: 'مباح', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'متى يبدأ وقت الصيام؟', option_a: 'طلوع الشمس', option_b: 'الفجر الصادق', option_c: 'الفجر الكاذب', option_d: 'شروق الشمس', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'ما هي زكاة الفطر؟', option_a: 'صدقة في رمضان', option_b: 'واجبة على كل مسلم', option_c: 'صاع من طعام', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'متى تخرج زكاة الفطر؟', option_a: 'أول رمضان', option_b: 'قبل صلاة العيد', option_c: 'بعد العيد', option_d: 'في أي وقت', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما مقدار زكاة الفطر؟', option_a: 'نصف صاع', option_b: 'صاع من الطعام', option_c: 'كيلو جرام', option_d: 'مد واحد', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما حكم صلاة التراويح؟', option_a: 'فرض', option_b: 'سنة مؤكدة', option_c: 'مستحبة', option_d: 'واجبة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'كم عدد ركعات صلاة التراويح عادة؟', option_a: '8 ركعات', option_b: '20 ركعة', option_c: '11 أو 13 ركعة', option_d: 'جميع ما سبق جائز', correct_answer: 'D', difficulty: 3 },
  { categoryName: 'رمضان', question_ar: 'ما هو دعاء الإفطار؟', option_a: 'اللهم لك صمت', option_b: 'ذهب الظمأ وابتلت العروق وثبت الأجر إن شاء الله', option_c: 'بسم الله', option_d: 'الحمد لله', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'من هم الذين رخص لهم الإفطار في رمضان؟', option_a: 'المسافر والمريض', option_b: 'الحائض والنفساء', option_c: 'كبير السن الذي لا يطيق', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما هي ليلة القدر خير من؟', option_a: 'ألف شهر', option_b: 'ألف يوم', option_c: 'مائة عام', option_d: 'خمسين عاماً', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'في أي سورة من القرآن ذكرت ليلة القدر؟', option_a: 'سورة البقرة', option_b: 'سورة القدر', option_c: 'سورة الدخان', option_d: 'سورة الرحمن', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'ما هو حكم تعجيل الإفطار؟', option_a: 'سنة', option_b: 'فرض', option_c: 'واجب', option_d: 'مستحب', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما حكم تأخير السحور؟', option_a: 'سنة', option_b: 'فرض', option_c: 'مكروه', option_d: 'حرام', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما اسم الشهر الذي يسبق رمضان؟', option_a: 'شعبان', option_b: 'رجب', option_c: 'محرم', option_d: 'ذو القعدة', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'ما حكم المضمضة والاستنشاق للصائم؟', option_a: 'مفطرة', option_b: 'لا تفطر ما لم يبالغ', option_c: 'حرام', option_d: 'مكروه', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما هي صلاة التهجد في رمضان؟', option_a: 'صلاة بعد العشاء', option_b: 'صلاة بعد الفجر', option_c: 'صلاة قبل المغرب', option_d: 'صلاة العصر', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما حكم الإفطار في رمضان للمسافر؟', option_a: 'حرام', option_b: 'جائز', option_c: 'مكروه', option_d: 'واجب', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'كم مرة ذكر رمضان في القرآن؟', option_a: 'مرة واحدة', option_b: 'مرتين', option_c: 'ثلاث مرات', option_d: 'أربع مرات', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'رمضان', question_ar: 'ما حكم تذوق الطعام للصائم؟', option_a: 'مفطر', option_b: 'لا بأس به ما لم يبتلعه', option_c: 'حرام', option_d: 'مكروه', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'في أي شهر أنزل القرآن؟', option_a: 'رمضان', option_b: 'شعبان', option_c: 'محرم', option_d: 'رجب', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'ما حكم صيام الست من شوال؟', option_a: 'فرض', option_b: 'سنة مستحبة', option_c: 'بدعة', option_d: 'مكروه', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما هي صلاة العيد؟', option_a: 'ركعتان بعد الفجر', option_b: 'ركعتان بعد الظهر', option_c: 'أربع ركعات', option_d: 'ركعتان بعد العصر', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما حكم صيام يوم العيد؟', option_a: 'جائز', option_b: 'حرام', option_c: 'مكروه', option_d: 'مستحب', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما فضل صيام رمضان كما ورد في الحديث؟', option_a: 'تكفير الذنوب', option_b: 'مضاعفة الحسنات', option_c: 'يغفر ما تقدم من الذنب', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما هو حكم الاعتكاف في رمضان؟', option_a: 'فرض', option_b: 'سنة', option_c: 'بدعة', option_d: 'مكروه', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما حكم صلاة التراويح في البيت؟', option_a: 'أفضل من المسجد', option_b: 'جائزة', option_c: 'لا تصح إلا في المسجد', option_d: 'بدعة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'رمضان', question_ar: 'متى ليلة القدر في العشر الأواخر؟', option_a: 'الليالي الوترية', option_b: 'الليالي الزوجية', option_c: 'كل الليالي', option_d: 'ليلة 27 فقط', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما حكم استقبال رمضان بالفرح والتهاني؟', option_a: 'بدعة', option_b: 'مستحب', option_c: 'حرام', option_d: 'مكروه', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'رمضان', question_ar: 'ما هي مفسدات الصيام؟', option_a: 'الأكل والشرب والجماع', option_b: 'النوم', option_c: 'المشي', option_d: 'القراءة', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'رمضان', question_ar: 'ما حكم صوم الحائض في رمضان؟', option_a: 'لا يصح وتقضي', option_b: 'يصح', option_c: 'مكروه', option_d: 'لا يصح ولا تقضي', correct_answer: 'A', difficulty: 2 },
  // ====== الحج والعمرة ======
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو الركن الأعظم في الحج؟', option_a: 'طواف الإفاضة', option_b: 'الوقوف بعرفة', option_c: 'السعي بين الصفا والمروة', option_d: 'رمي الجمرات', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'كم مرة فرض الحج على المسلم؟', option_a: 'مرة واحدة في العمر', option_b: 'كل عام', option_c: 'مرة كل خمس سنوات', option_d: 'مرتين في العمر', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو الإحرام؟', option_a: 'نية الدخول في الحج أو العمرة', option_b: 'لبس ملابس خاصة', option_c: 'التلبية', option_d: 'الغسل', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو الطواف؟', option_a: 'المشي بين الصفا والمروة', option_b: 'الدوران حول الكعبة', option_c: 'الوقوف بعرفة', option_d: 'رمي الجمرات', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو السعي؟', option_a: 'الدوران حول الكعبة', option_b: 'المشي بين الصفا والمروة', option_c: 'الذهاب إلى منى', option_d: 'الوقوف بعرفة', correct_answer: 'B', difficulty: 1 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي الجمرات الثلاث؟', option_a: 'جمرة العقبة والوسطى والصغرى', option_b: 'جمرة الكبرى والوسطى والصغرى', option_c: 'جمرة منى وعرفة ومزدلفة', option_d: 'جمرة العقبة فقط', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو يوم عرفة؟', option_a: 'اليوم التاسع من ذي الحجة', option_b: 'اليوم العاشر من ذي الحجة', option_c: 'اليوم الثامن من ذي الحجة', option_d: 'اليوم الحادي عشر', correct_answer: 'A', difficulty: 1 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما معنى التلبية؟', option_a: 'دعاء خاص', option_b: 'قول لبيك اللهم لبيك', option_c: 'ذكر الله', option_d: 'الصلاة على النبي', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو الحجر الأسود؟', option_a: 'حجر من الجنة', option_b: 'حجر كريم', option_c: 'حجر عادي', option_d: 'حجر منزل من السماء', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي مزدلفة؟', option_a: 'مكان في منى', option_b: 'مكان بين عرفة ومنى', option_c: 'مكان في مكة', option_d: 'مكان في المدينة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'كم عدد أيام الحج؟', option_a: '4 أيام', option_b: '5 أيام', option_c: '6 أيام', option_d: '7 أيام', correct_answer: 'C', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو يوم النحر؟', option_a: 'يوم عرفة', option_b: 'اليوم العاشر من ذي الحجة', option_c: 'اليوم الحادي عشر', option_d: 'اليوم الثاني عشر', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي أيام التشريق؟', option_a: '8 و 9 و 10 ذي الحجة', option_b: '11 و 12 و 13 ذي الحجة', option_c: '10 و 11 و 12 ذي الحجة', option_d: '9 و 10 و 11 ذي الحجة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما حكم العمرة؟', option_a: 'فرض', option_b: 'سنة مؤكدة', option_c: 'واجبة', option_d: 'مستحبة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو طواف الوداع؟', option_a: 'طواف العمرة', option_b: 'طواف آخر الحج', option_c: 'طواف القدوم', option_d: 'طواف الإفاضة', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'من أول من بنى الكعبة؟', option_a: 'النبي محمد ﷺ', option_b: 'إبراهيم عليه السلام', option_c: 'إسماعيل عليه السلام', option_d: 'آدم عليه السلام', correct_answer: 'D', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو الهدي في الحج؟', option_a: 'الصدقة', option_b: 'ما يذبح من الأنعام تقرباً لله', option_c: 'الصيام', option_d: 'الصلاة', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي محظورات الإحرام؟', option_a: 'لبس المخيط للمرأة', option_b: 'لبس المخيط للرجل', option_c: 'النوم', option_d: 'الأكل', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو طواف القدوم؟', option_a: 'طواف عند الوصول إلى مكة', option_b: 'طواف الوداع', option_c: 'طواف العمرة', option_d: 'طواف الإفاضة', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما معنى المبيت في منى؟', option_a: 'الإقامة في منى أيام التشريق', option_b: 'النوم في عرفة', option_c: 'الذهاب إلى مزدلفة', option_d: 'البقاء في مكة', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو الركن الثالث من أركان الحج بعد الإحرام والوقوف؟', option_a: 'طواف الإفاضة', option_b: 'السعي', option_c: 'رمي الجمرات', option_d: 'الحلق', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو حكم الحج عن الغير؟', option_a: 'لا يجوز', option_b: 'يجوز في النيابة', option_c: 'مكروه', option_d: 'حرام', correct_answer: 'B', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'من هم الذين لا يجب عليهم الحج؟', option_a: 'الفقير والمريض والعاجز', option_b: 'الغني فقط', option_c: 'الرجل فقط', option_d: 'الشاب فقط', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي أشهر الحج؟', option_a: 'شوال وذو القعدة وذو الحجة', option_b: 'رجب وشعبان ورمضان', option_c: 'محرم وصفر وربيع', option_d: 'شوال ومحرم وصفر', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما حكم صيام يوم عرفة لغير الحاج؟', option_a: 'فرض', option_b: 'سنة مؤكدة', option_c: 'مكروه', option_d: 'حرام', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو الحلق أو التقصير في الحج؟', option_a: 'حلق الشعر أو قصه للرجال', option_b: 'قص الأظافر', option_c: 'حلق اللحية', option_d: 'قص الشارب', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي صفة الإحرام للرجل؟', option_a: 'يلبس إزاراً ورداء', option_b: 'يلبس بدلة خاصة', option_c: 'يلبس ثياباً بيضاء', option_d: 'يلبس أي ثياب', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي صفة الإحرام للمرأة؟', option_a: 'تلبس ما شاءت من الثياب غير متبرجة', option_b: 'تلبس أبيض فقط', option_c: 'تلبس أسود فقط', option_d: 'تغطي وجهها', correct_answer: 'A', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو فضل يوم عرفة كما ورد في الحديث؟', option_a: 'أفضل أيام الدنيا', option_b: 'يكفر سنتين', option_c: 'يعتق الله فيه الرقاب من النار', option_d: 'جميع ما سبق', correct_answer: 'D', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما معنى الطواف المطلق؟', option_a: 'طواف غير مقيد بعمرة أو حج', option_b: 'طواف الوداع', option_c: 'طواف القدوم', option_d: 'طواف الإفاضة', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي صلاة الطواف؟', option_a: 'ركعتان خلف مقام إبراهيم', option_b: 'ركعتان في الحجر', option_c: 'أربع ركعات', option_d: 'ركعة واحدة', correct_answer: 'A', difficulty: 3 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هو حكم التكبير في أيام التشريق؟', option_a: 'فرض', option_b: 'سنة', option_c: 'بدعة', option_d: 'مكروه', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما معنى طواف الإفاضة؟', option_a: 'طواف العمرة', option_b: 'طواف الحج بعد الوقوف', option_c: 'طواف القدوم', option_d: 'طواف الوداع', correct_answer: 'B', difficulty: 2 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما هي المسافة بين الصفا والمروة؟', option_a: '395 متراً تقريباً', option_b: '500 متر', option_c: '300 متر', option_d: '450 متراً', correct_answer: 'A', difficulty: 4 },
  { categoryName: 'الحج والعمرة', question_ar: 'ما حكم من ترك ركناً من أركان الحج؟', option_a: 'يفسد حجه', option_b: 'لا يصح حجه حتى يأتي به', option_c: 'عليه دم', option_d: 'حجه صحيح', correct_answer: 'B', difficulty: 3 },
];
export async function seedDatabase(): Promise<void> {
  await initDb();
  initializeSchema();

  const row = queryOne('SELECT COUNT(*) as count FROM categories');
  if (row && (row.count as number) > 0) {
    console.log('✅ قاعدة البيانات تحتوي بالفعل على بيانات. تخطي البذر.');
    return;
  }

  const categoryIds: Record<string, number> = {};

  for (const cat of categories) {
    const id = executeInsert('INSERT INTO categories (name_ar, name_en) VALUES (?, ?)', [cat.name_ar, cat.name_en]);
    categoryIds[cat.name_ar] = id;
  }

  let count = 0;
  for (const q of questions) {
    const catId = categoryIds[q.categoryName];
    if (catId) {
      executeInsert(
        'INSERT INTO questions (category_id, question_ar, option_a, option_b, option_c, option_d, correct_answer, difficulty, source) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)',
        [catId, q.question_ar, q.option_a, q.option_b, q.option_c, q.option_d, q.correct_answer, q.difficulty, q.source || null],
      );
      count++;
    }
  }

  console.log(`✅ تم بذر قاعدة البيانات بنجاح! ${count} سؤال في ${Object.keys(categoryIds).length} تصنيف.`);
}

if (require.main === module) {
  (async () => {
    await initDb();
    seedDatabase();
  })();
}
